### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by weihao** [Drawethree/spigot-hibernate-demo#2]
[02:08:07] [Server thread/ERROR]: Error occurred while enabling SpigotHibernateDemo v1.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at dev.drawethree.spigothibernatedemo.SpigotHibernateDemo.onEnable(SpigotHibernateDemo.java:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.internal.CoreMessageLogger (implementation not found in org.bukkit.plugin.java.PluginClassLoader@7eb7f67a)
        at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2564) ~[?:?]
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530) ~[?:?]
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516) ~[?:?]
        at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:28) ~[?:?]
        at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:24) ~[?:?]
        at org.hibernate.cfg.Configuration.<clinit>(Configuration.java:87) ~[?:?]
        ... 12 more

**Comment by lukasjakobi** [comment]
Got the same error, quick google search wasn't too helpful either

**Comment by lukasjakobi** [comment]
Hey, me again!

I looked into the issue a little further, but was stuck at first. This isn't a common issue as it seems. Turns out I had to disable the `minimizeJar` option in the maven-shade-plugin. While the jar got minimized, the jboss.logging.logger dependency was simply removed from the generated class sources.

Check your `pom.xml` if it contains such a section:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
      <execution>
        <phase>package</phase>
        <goals>
          <goal>shade</goal>
        </goals>
        <configuration>
          <minimizeJar>true</minimizeJar>
        </configuration>
      </execution>
    </executions>
  </plugin>
```

**Comment by weihao** [comment]
@lukasjakobi thanks, moved pass that error but got a new one, have you seen this?

```
Error occurred while enabling SpigotHibernateDemo v1.0-SNAPSHOT (Is it up to date?)
org.hibernate.internal.util.config.ConfigurationException: Unable to perform unmarshalling at line number 0 and column 0 in FILE C:\plugins-testing\plugins\SpigotHibernateDemo\hibernate.cfg.xml. Message: null
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:134) ~[?:?]
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:66) ~[?:?]
        at org.hibernate.boot.cfgxml.internal.ConfigLoader.loadConfigXmlFile(ConfigLoader.java:76) ~[?:?]
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.configure(StandardServiceRegistryBuilder.java:258) ~[?:?]
        at org.hibernate.cfg.Configuration.configure(Configuration.java:301) ~[?:?]
        at dev.drawethree.spigothibernatedemo.SpigotHibernateDemo.onEnable(SpigotHibernateDemo.java:24) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278) ~[?:?]
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:421) ~[?:?]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721) ~[?:?]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662) ~[?:?]
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:123) ~[?:?]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122) ~[?:?]
        at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155) ~[?:?]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276) ~[?:?]
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:421) ~[?:?]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721) ~[?:?]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662) ~[?:?]
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:123) ~[?:?]
        ... 16 more
```

**Comment by lukasjakobi** [comment]
Your hibernate.cfg.xml seems to be misconfigured. Can you share it please?

**Comment by weihao** [comment]
```
<!DOCTYPE hibernate-configuration PUBLIC
        "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
        "http://www.hibernate.org/dtd/hibernate-configuration-3.0.dtd">

<hibernate-configuration>

    <session-factory>

        <!-- JDBC Database connection settings -->
        <property name="connection.driver_class">com.mysql.cj.jdbc.Driver</property>
        <property name="connection.url">jdbc:mysql://localhost:3306/db?useSSL=false</property>
        <property name="connection.username">root</property>
        <property name="connection.password">password</property>

        <!-- JDBC connection pool settings -->
        <property name="connection.pool_size">1</property>

        <!-- Select our SQL dialect -->
        <property name="dialect">org.hibernate.dialect.MySQLDialect</property>

        <!-- Echo the SQL to stdout -->
        <property name="show_sql">false</property>

        <!-- Format the SQL -->
        <property name="format_sql">false</property>

		<!-- Set the current session context -->
		<property name="current_session_context_class">thread</property>

        <!-- Handles the entity table changes -->
        <property name="hibernate.hbm2ddl.auto">update</property>

    </session-factory>

</hibernate-configuration>
```

I think some lib is missing from the error msg `Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory`

What java version do you use to compile and run the server?
